- group:
    enabled: true
    name: dollar
- group:
    enabled: true
    name: generalise
- ignore:
    name: Use lambda-case
- ignore:
    name: Use list comprehension
- ignore:
    name: Use newtype instead of data
- ignore:
    name: Use tuple-section
